[build]
rustflags = [
    "--cfg=web_sys_unstable_apis",
    "-Z",
    "wasm-c-abi=spec",
    "-Z",
    "location-detail=none",
]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort", "optimize_for_size"]